### PR TITLE
Volume cleanup and 100% CPU issues

### PR DESCRIPTION
**Pull request by schmist**
Fixes the following two issues (for more information see commit comments):
- missing volume cleanup
- 100% CPU issue on MacOS systems (also see probably related `docker-java` issue [here](https://github.com/docker-java/docker-java/issues/1350))

### CODE REVIEW

**Comment by adrianskrobaczrevolut** [comment]
Looks great, thank you 👍 merged it

**Comment by schmist** [comment]
Would it be possible to create a release with these changes merged? Otherwise we need to build it ourselves since the 100% CPU issue is a blocker for us.

**Comment by adrianskrobaczrevolut** [comment]
Hey @schmist,
Sure just released it [0.3.5](https://plugins.gradle.org/plugin/com.revolut.jooq-docker/0.3.5) 🙂

**Comment by schmist** [comment]
Thanks!

**Pull request merged**
